name: flutter3
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #cupertino_icons: ^0.1.0

dev_dependencies:

  flutter_test:
    sdk: flutter
  firebase_database: "^1.0.3"
  css_colors: ^1.0.0
  firebase_core: "^0.2.3"
  flutter_facebook_login: "^1.1.1"
  http: "^0.11.3+16"
  google_maps_webservice: "^0.0.5"
  firebase_messaging: "^1.0.0"
  intl: "^0.15.6"
  flutter_webview_plugin: "^0.2.1"
  dio: "^0.0.14"
  io: "^0.3.2+1"
  image_picker: "^0.4.5"
  firebase_storage: "^0.3.5"
  shared_preferences: "^0.4.2"
  image: "^2.0.4"
  image_cropper: "^0.0.4"
  flutter_native_image:
    git: https://github.com/btastic/flutter_native_image.git
  path_provider: ^0.4.1
  secure_string: ^2.0.0
  firebase_auth: ^0.5.15
  latlong: ^0.5.3
  cached_network_image: ^0.4.1+1
  camera: ^0.2.1









# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/mul.png
   - assets/thumbsOutLogo.png
   - assets/fb.png
   - assets/comment50.png
   - assets/maleIcon65.png
   - assets/femaleIcon65.png
   - assets/switchCamera65.png
   - assets/appIcon83.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
